######################### HOME #########################
home:
    path: /
    controller: App\Controller\HomeController::index
########################################################
############## FORMULAIRE UTILISATEUR #################
register:
    path: /register
    controller: App\Controller\AccountController:register

login:
    path: /login
    controller: App\Controller\AccountController::login

logout:
    path: /logout
    controller: App\Controller\AccountController:logout

account:
    path: /account/{username}
    controller: App\Controller\UsersController:index

account_edit:
    path: /account/edit
    controller: App\Controller\AccountController:editAccount

account_password_edit:
    path: /account/password/edit
    controller: App\Controller\AccountController:editPassword
#######################################################
################## ADMINISTRATION #####################
admin_login:
    path: /admin/login
    controller: App\Controller\AdminAccountController:login

admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminAccountController:logout

admin_products:
    path: /admin/products
    controller: App\Controller\AdminProductController:index
#######################################################
##################### PRODUITS ########################
add_product:
    path: /product/create
    controller: App\Controller\ProductsController:create
product:
    path: /product/{id}
    controller: App\Controller\ProductsController:index
    #######################################################

league:
    path: /league/{league_name}
    controller: App\Controller\LeaguesController:index

cart:
    path: /car
    controller: App\Controller\CartController::index