########################################################
######################## HOME ##########################
########################################################
home:
    path: /
    controller: App\Controller\HomeController::index
########################################################
############# FORMULAIREs UTILISATEUR ##################
########################################################
#------------ Formulaire d'inscription ---------------#
register:
    path: /register
    controller: App\Controller\AccountController:register
#-------------- Formulaire connexion -----------------#
login:
    path: /login
    controller: App\Controller\AccountController::login
#------------- Formulaire déconnexion ----------------#
logout:
    path: /logout
    controller: App\Controller\AccountController:logout
#--------------- Edition du compte ------------------#
account_edit:
    path: /account/edit
    controller: App\Controller\AccountController:editAccount
#------------ Edition du mot de passe ---------------#
account_password_edit:
    path: /account/password/edit
    controller: App\Controller\AccountController:editPassword
#------------ Ajout + Edition de la livraison ---------------#
account_livraison_create:
    path: /account/livraison/create
    controller: App\Controller\LivraisonController:create
account_livraison_edit:
    path: /account/livraison/{id}/edit
    controller: App\Controller\LivraisonController:edit
account_livraison_delete:
    path: /account/livraison/{id}/delete
    controller: App\Controller\LivraisonController:delete
#-------------- Ajout + Edition du paiement -----------------#
account_bank_create:
    path: /account/bank/create
    controller: App\Controller\BankController:create
account_bank_edit:
    path: /account/bank/{id}/edit
    controller: App\Controller\BankController:edit
account_bank_delete:
    path: /account/bank/{id}/delete
    controller: App\Controller\BankController:delete
#---------- Accès au compte utilisateur -------------#
account:
    path: /account/{username}
    controller: App\Controller\UsersController:index
#######################################################
################## ADMINISTRATION #####################
#######################################################
#-------------- Formulaire connexion -----------------#
admin_login:
    path: /admin/login
    controller: App\Controller\AdminAccountController:login
#------------- Formulaire déconnexion ----------------#
admin_logout:
    path: /admin/logout
    controller: App\Controller\AdminAccountController:logout
#-------------- Panel administration -----------------#
admin_dashboard:
    path: /admin/
    controller: App\Controller\AdminDashboardController:index
#++++++++++++++ Gestion des produits +++++++++++++++++#
admin_products:
    path: /admin/products/{page<\d+>?1}
    controller: App\Controller\AdminProductController:index

admin_product_add:
    path: admin/product/create
    controller: App\Controller\AdminProductController:create

admin_product_edit:
    path: /admin/product/{id}/edit
    controller: App\Controller\AdminProductController:edit

admin_product_delete:
    path: /admin/product/{id}/destroy
    controller: App\Controller\AdminProductController:destroy
#+++++++++++++++++++++++++++++++++++++++++++++++++++++#
#++++++++++ Gestion des utilisateurs +++++++++++++++++#
admin_users:
    path: /admin/users/{page<\d+>?1}
    controller: App\Controller\AdminUsersController:index

admin_user_edit:
    path: /admin/user/{id}/edit
    controller: App\Controller\AdminUsersController:edit

admin_user_delete:
    path: /admin/user/{id}/destroy
    controller: App\Controller\AdminUsersController:destroy
#-----------------------------------------------------#
#######################################################
##################### PRODUITS ########################
#######################################################
product:
    path: /product/{id}
    controller: App\Controller\ProductsController:index

###########################################################
##################### UTILISATEURS ########################

###########################################################
league:
    path: /league/{league_name}
    controller: App\Controller\LeaguesController:index

cart:
    path: /cart
    controller: App\Controller\CartController::index