home:
    path: /
    controller: App\Controller\HomeController::index

product:
    path: /product/{id}
    controller: App\Controller\ProductsController:index

league:
    path: /ligue/{league_name}
    controller: App\Controller\LeaguesController:index

cart:
    path: /panier
    controller: App\Controller\CartController::index